version: '1.0'
services:
  postgres:
    build: ./docker/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432


volumes:
  postgres-volume: